### PR TITLE
Dependency updates etc.

### PR DESCRIPTION
**Pull request by ahmett**
Gateway builds will proceed after this merged and tagged properly.

https://github.com/payconn/nestpay/pull/30
https://github.com/payconn/garanti/pull/13
https://github.com/payconn/ipara/pull/11
https://github.com/payconn/vakif/pull/6
https://github.com/payconn/wirecard/pull/6

**Important footnote** : Before merging gateway pull requests please sure that packagist is updated latest version for this library. ( This may cause build errors on travis )

### CODE REVIEW

**Comment by muratsac** [comment]
> /cc @muratsac

hi @ahmett,

thank you for PRs. I have a questions:
1. how does benefit us?
2. we have currently PayConn users. Will they no longer get updates without upgrading the php version?

**Comment by ahmett** [comment]
Hello @muratsac, it was a mistake 🤦‍♂️ 

This update aims the latest version of packages (like frameworks or libraries) that using guzzle 7, but I completely understand your concern. I will add fallback versions.

**Comment by ahmett** [comment]
Hey @muratsac, all set to go 🚀

**Review by muratsac — APPROVED** [review]

**Pull request merged**
